# Generated by Django 4.1.3 on 2023-01-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamahasiswa',
            old_name='jenis_kelamin',
            new_name='gander',
        ),
        migrations.AlterField(
            model_name='datamahasiswa',
            name='npm',
            field=models.IntegerField(null=True),
        ),
    ]
